# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=250)),
                ('med_description', models.CharField(max_length=10000)),
                ('med_price', models.CharField(max_length=250)),
                ('med_logo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=250)),
                ('product_logo', models.CharField(max_length=1000)),
                ('product_description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=250)),
                ('salts', models.CharField(max_length=250)),
                ('salts_quantity', models.CharField(max_length=100)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.Medicine')),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.Products'),
        ),
    ]
