# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(default='NA', max_length=250),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='med_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='specification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salts', to='medicines.Medicine'),
        ),
    ]
