# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-15 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_auto_20180411_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='specification',
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
