# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-04-15 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_auto_20180415_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=100)),
                ('salt_quantity', models.CharField(max_length=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.Medicine')),
            ],
        ),
    ]
